---
name: Feature request
about: Suggest an idea for this project
title: ''
labels: enhancement
assignees: ''

---

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**
A clear and concise description of what you want to happen.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered.


**Scope**
<!-- Please include a list of what the feature should and shouldn't do by filling in the table below.
'Must' implies that the feature should not ship without this capability.  
'Should' is something we should push hard for, but is not absolutely required to ship.
'Could' is a nice-to-have; a good stretch goal that isn't painful if we don't achieve it.
'Won't' is a clear statement that the proposal/feature will intentionally not have that capability.
This list will evolve and grow as the proposal becomes more refined over time.
A good rule of thumb is to start your proposal with no more than 7 high-level requirements.
-->
| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |


**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context or screenshots about the feature request here.